# Generated by Django 4.0.2 on 2022-02-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_rename_username_user_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nome',
            field=models.CharField(max_length=100, verbose_name='Nome'),
        ),
    ]
